services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatgram-backend
    restart: unless-stopped

    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

